`ifndef DISPATCHER_CFG_PARAMETER__SV
`define DISPATCHER_CFG_PARAMETER__SV

`define DISP_CFG_CLST_N      4
`define DISP_CFG_CU_N        4

`define DISP_CFG_CFG_ADDR_W  32
`define DISP_CFG_CFG_DATA_W  32
`define DISP_CFG_CFG_STRB_W  (`DISP_CFG_CFG_DATA_W/8)

`define DISP_CFG_CORE_ID_W   6
`define DISP_CFG_CORE_ADDR_W 12
`define DISP_CFG_CORE_DATA_W 32
`define DISP_CFG_CORE_STRB_W (`DISP_CFG_CORE_DATA_W/8)

`endif
